version: '3'

services:
  samba:
    image: dperson/samba
    container_name: samba
    environment:
      TZ: ${TZ}
    networks:
      - proxy
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "445:445/tcp"
    read_only: true
    tmpfs:
      - /tmp
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - /data:/data:z
    command: '-s "Data;/data;yes;no;no;${USER};all;all;Data" -u "${USER};${PASSWORD};${USER};${USER};${LOCAL_USER}" -n '

networks:
  proxy:
    external: true