version: "3"

networks:
  proxy:
    external: true

services:
  heimdall:
    image: lscr.io/linuxserver/heimdall
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - ./config:/config
    ports:
      - 7780:80
      - 7443:443
    restart: unless-stopped
    networks:
     - proxy
    labels:
     - "traefik.enable=true"
     - "traefik.http.routers.heimdall.rule=Host(`dashboard.${DOMAIN}.${TLD}`)"
     - "traefik.http.routers.heimdall.entrypoints=https"
     - "traefik.http.routers.heimdall.tls=true"
     - "traefik.http.routers.heimdall.tls.certresolver=letsencrypt"
     - "traefik.http.services.heimdall.loadbalancer.server.port=443"
     - "traefik.http.services.heimdall.loadbalancer.server.scheme=https"
     - 'traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https,wss'
     - 'traefik.http.routers.heimdall.middlewares=authelia@docker'
     # Watchtower Update
     - "com.centurylinklabs.watchtower.enable=true"
