version: "3"

networks:
  proxy:
    external: true

services:
  unifi:
    image: lscr.io/linuxserver/unifi-controller
    container_name: unifi
    environment:
      - PUID=1000
      - PGID=1000
      - MEM_LIMIT=1024 
      - MEM_STARTUP=1024
    volumes:
      - ./config:/config
    networks:
      - proxy
    ports:
      - 8443:8443
      - 3478:3478/udp
      - 10001:10001/udp
      - 8080:8080
      - 1901:1900/udp #optional
      - 8843:8843 #optional
      - 8880:8880 #optional
      - 6789:6789 #optional
      - 5514:5514/udp #optional
    restart: unless-stopped
    labels:
     - "traefik.enable=true"
     - "traefik.http.routers.unifi.rule=Host(`unifi.${DOMAIN}.${TLD}`)"
     - "traefik.http.routers.unifi.entrypoints=https"
     - "traefik.http.routers.unifi.tls=true"
     - "traefik.http.routers.unifi.tls.certresolver=letsencrypt"
     - "traefik.http.services.unifi.loadbalancer.server.port=8443"
     - "traefik.http.services.unifi.loadbalancer.server.scheme=https"
     - 'traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https,wss'
     # Watchtower Update
     - "com.centurylinklabs.watchtower.enable=true"
