version: "3.8"

networks:
  proxy:
    external: true

services:
  wireguard:
    environment:
      - WG_HOST=${DOMAIN}.${TLD}
      - WG_PORT=51820
      - WG_DEFAULT_ADDRESS=10.8.0.x
      - WG_DEFAULT_DNS=192.168.168.1
      - WG_MTU=1420
      - WG_ALLOWED_IPS=192.168.168.0/24, 10.0.1.0/24
      
    image: weejewel/wg-easy
    container_name: wireguard
    volumes:
      - ./data:/etc/wireguard
    networks:
      - proxy
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    labels:
     - "traefik.enable=true"
     - "traefik.http.routers.wireguard.rule=Host(`wireguard.${DOMAIN}.${TLD}`)"
     - "traefik.http.routers.wireguard.entrypoints=https"
     - "traefik.http.routers.wireguard.tls=true"
     - "traefik.http.routers.wireguard.tls.certresolver=letsencrypt"
     - "traefik.http.services.wireguard.loadbalancer.server.port=51821"
     # Watchtower Update
     - "com.centurylinklabs.watchtower.enable=true"
